services:
  n8n:
    image: n8nio/n8n:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    environment:
      GENERIC_TIMEZONE: Europe/Berlin
      TZ: Europe/Berlin
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: 443
      N8N_PROTOCOL: https
    ports:
      - 10008:443
    volumes:
      - data:/home/node/.n8n

volumes:
  data:
