services:
  n8n:
    image: n8n/n8n:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GENERIC_TIMEZONE: Europe/Berlin
      TZ: Europe/Berlin
      N8N_HOST: ${HOSTNAME}
      N8N_PORT: ${PORT}
      N8N_PROTOCOL: https
    ports:
      - 10008:5678
    volumes:
      - data:/home/node/.n8n

volumes:
  data:
